name = "pythonic-peano-arithmetic"
compatibility_date = "2026-07-27"

[assets]
directory = "./site"
not_found_handling = "404-page"
html_handling = "auto-trailing-slash"

[[routes]]
pattern = "peano.yusuke-hayashi.com"
custom_domain = true
